defmodule Kantan.Repo.TenantMigrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "users_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop constraint(:users, "users_tenant_id_fkey")

    drop table(:users, prefix: prefix())
  end
end