defmodule Kantan.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text
    end

    create unique_index(:tenants, [:name], name: "tenants_unique_name_index")

    create unique_index(:tenants, [:slug], name: "tenants_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:tenants, [:slug], name: "tenants_unique_name_index")

    drop_if_exists unique_index(:tenants, [:name], name: "tenants_unique_name_index")

    drop table(:tenants)
  end
end